sudo: required
dist: trusty

language: node_js
node_js:
  - 8

env:
  global:
    - secure: "p1lPppq7SXD3DLtZ2AIAY5ML6V8HlINNwuKnf95d1pmJ8K2xUvVhFbscKpn/9qN2H5MvlTIcW1FkQmu9fCVtvoY1oPw1WdgCwBWfkj4zS7bfiLTMU192U11POXm3O10Abp0eStMNII11nqslB4G1LU+VpUkkjey4pKMBnVH+qEPZle+aF9ijfAQXKq9pQ2VQhVaiuRDlDgCBv+yqYCuMAx9nL1n5WSRFsbzGBCy6eT/Z3BuRfqj4kxaF3HxIsWZZ9oXKgR1AgNR9dvVAzc2HlWG2bUTo7yaKkLW/584c792E6I3nkz9HNb6wP5QdBXKGS4scoD3yFFcZlWvleRZy138VSu+AeFRbGcmWRDaR3iNidc7fyVNFAqvI57d1st1oqa6FD276aR+77ePQQd6WGaML1T/j+ZP/JqbyWJAxd0a3nWQ775to2ffw87EE43X6FJPBuJWWn8dw0cq6VAaZZSvn1vzR/emuU/yhvvNKER9N28b3QWM4djNjqkMChCLsoSeMP1RbKqvhPtVjoBIqoEihvzXgSfzlKDUtwYdNGSxPrWAwKworyA2n8NwDp8/8/VMykl+P4U3BXawr/Nrx1HFWL4clEV3/Pez1yYS4MJQztFTbinG6GXPI2NYDM/zUJaaN3DWKEEBzUlER0bvllQEmNMEiNKBfA8G957bjV40="

install:
  - npm install
  - npm install -g angular-cli-ghpages

script:
  - npm run test
  - npm run build
  - npm run build-ghpages

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ] ; then angular-cli-ghpages --dir="dist-ghpages" --repo="https://${GH_TOKEN}@github.com/jgodi/jgodi-angular-library-starter-kit.git" --name="Sr. Travis" --email="hi@travis.org"; fi
